#!/bin/sh
#  If you log back in after quitting an encrypted connection, will the
#  new connection be encrypted? - No, there can be several log ins and 
#  some can be encrypted and others not.  If you want encryption you have 
#  to generate keys to do it and handshake.
#     A franco1 client and server will be started with encryption turned on.
#     The host port of the Passive Server for franco1 is 20500.
#     From the blank shell try the following:
#   ->  active client command> quit
#   ->  shell prompt> telnet localhost 8150
#       Trying 127.0.0.1...
#       Connected to localhost (127.0.0.1).
#       Escape character is '^]'.
#       COMMENT: Monitor Version 2.2
#       REQUIRE: IDENT
#       WAITING:
#  ->   ident franco1
#       REQUIRE: ALIVE
#       WAITING:
#       alive G5EIBHX0UPBDLCRZ8A1
#       RESULT: ALIVE Identity has been verified.
#       WAITING:
MONITOR="localhost"
xterm -T "Franco1 Server" -fn 10x20 -bg papayawhip -cr red -geometry 80x18+500+20 -e java StartServer ${MONITOR} 8150 20500 franco1 &
xterm -T "Franco1 Client" -fn 10x20 -bg papayawhip -cr red -geometry 80x18+500+420 -e java StartClient ${MONITOR} 8150 20500 franco1 &
xterm -T "Shell" -fn 10x20 -bg papayawhip -cr red -geometry 80x18+0+420  &
